# passing SSH_HOST and SSH_PASSWORD in the menu
variables:
  YAML_FILE: "config.yml"

  
stages:
  - check_env
  - vault_query
  - build

check_env:
  stage: check_env
  image: python:3.10
  script:
    - python3 inventories/equinix/check_env.py

vault_query:
  stage: vault_query
  image: fedora:37
  variables:
    VAULT_ADDRESS: http://10.0.0.48:8200/
    VAULT_TOKEN: s.zlOfmgNtfTiMUpEFspZhspWg
    SECRET_PATH:  equinix
  script:
      - dnf install -y dnf-plugins-core
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      - dnf -y update
      - dnf install -y jq vault
      - setcap -r /usr/bin/vault
      - export VAULT_TOKEN="${VAULT_TOKEN}"
      - export VAULT_ADDR="${VAULT_ADDRESS}"
      - sudo -E vault kv get -format=json ansiblesafe/equinix | jq -r '.data.data' > $YAML_FILE
  artifacts:
    paths:
      - $YAML_FILE
  only:
    - main

build:
  stage: build
  image: fedora:37
  variables:
    SSH_USER:  lab-user
    CICD_PIPELINE: 'true'
    ENV_USERNAME:  lab-user
    DOMAIN: qubinodelab.io
    FORWARDER: '147.75.207.207'
    ACTIVE_BRIDGE: 'false'
    INTERFACE: bond0
    GIT_REPO: https://github.com/tosin2013/qubinode_navigator.git
    INVENTORY: equinix
  allow_failure: false
  script:
    - ls -la $YAML_FILE
    - dnf install wget openssh-clients sshpass -y
    - mkdir -p ~/.ssh/
    - ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    - sshpass -p "$SSH_PASSWORD" ssh-copy-id -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST"
    - scp $YAML_FILE "$SSH_USER"@"$SSH_HOST":/tmp/
    - sed -i 's|export GIT_REPO=.*|GIT_REPO="'$GIT_REPO'"|g' rocky-linux-hypervisor.sh
    - ssh "$SSH_USER"@"$SSH_HOST"  'env CICD_PIPELINE="'$CICD_PIPELINE'" SSH_PASSWORD="'$SSH_PASSWORD'"
        ENV_USERNAME="'$ENV_USERNAME'" DOMAIN="'$DOMAIN'" FORWARDER="'$FORWARDER'" INVENTORY="'$INVENTORY'"
        ACTIVE_BRIDGE="'$ACTIVE_BRIDGE'" INTERFACE="'$INTERFACE'" sudo -E bash -s' < rocky-linux-hypervisor.sh
        
  only:
    - main
