"""
Tests for DAG helper functions - User configuration helpers
Tests the fix for hardcoded root user issue in DAG files.
"""

import os
import sys
import pytest
from pathlib import Path

# Add airflow/dags to path to import dag_helpers
sys.path.insert(0, str(Path(__file__).parent.parent / "airflow" / "dags"))

from dag_helpers import (
    get_ssh_user,
    get_ssh_key_path,
    get_inventory_dir,
    get_vault_password_file,
    get_pull_secret_path,
    ssh_to_host_command,
    ssh_to_host_script,
)


class TestUserConfigurationHelpers:
    """Test user configuration helper functions."""

    def test_get_ssh_user_default(self):
        """Test get_ssh_user returns current user by default."""
        # Clear env var if set
        os.environ.pop('QUBINODE_SSH_USER', None)
        
        user = get_ssh_user()
        # Should return either USER env var or 'root'
        assert user in [os.environ.get('USER', 'root'), 'root']
        assert isinstance(user, str)
        assert len(user) > 0

    def test_get_ssh_user_from_env(self):
        """Test get_ssh_user respects QUBINODE_SSH_USER env var."""
        os.environ['QUBINODE_SSH_USER'] = 'testuser'
        
        user = get_ssh_user()
        assert user == 'testuser'
        
        # Cleanup
        os.environ.pop('QUBINODE_SSH_USER', None)

    def test_get_ssh_key_path_default(self):
        """Test get_ssh_key_path returns ~/.ssh/id_rsa by default."""
        os.environ.pop('QUBINODE_SSH_KEY_PATH', None)
        
        key_path = get_ssh_key_path()
        assert key_path.endswith('/.ssh/id_rsa')
        assert '~' not in key_path  # Should be expanded

    def test_get_ssh_key_path_from_env(self):
        """Test get_ssh_key_path respects QUBINODE_SSH_KEY_PATH env var."""
        test_path = '/custom/path/key.pem'
        os.environ['QUBINODE_SSH_KEY_PATH'] = test_path
        
        key_path = get_ssh_key_path()
        assert key_path == test_path
        
        # Cleanup
        os.environ.pop('QUBINODE_SSH_KEY_PATH', None)

    def test_get_inventory_dir_default(self):
        """Test get_inventory_dir returns ~/.generated by default."""
        os.environ.pop('QUBINODE_INVENTORY_DIR', None)
        
        inv_dir = get_inventory_dir()
        assert inv_dir.endswith('/.generated')
        assert '~' not in inv_dir  # Should be expanded

    def test_get_inventory_dir_from_env(self):
        """Test get_inventory_dir respects QUBINODE_INVENTORY_DIR env var."""
        test_dir = '/opt/inventories'
        os.environ['QUBINODE_INVENTORY_DIR'] = test_dir
        
        inv_dir = get_inventory_dir()
        assert inv_dir == test_dir
        
        # Cleanup
        os.environ.pop('QUBINODE_INVENTORY_DIR', None)

    def test_get_vault_password_file_default(self):
        """Test get_vault_password_file returns ~/.vault_password by default."""
        os.environ.pop('QUBINODE_VAULT_PASSWORD_FILE', None)
        
        vault_file = get_vault_password_file()
        assert vault_file.endswith('/.vault_password')
        assert '~' not in vault_file  # Should be expanded

    def test_get_vault_password_file_from_env(self):
        """Test get_vault_password_file respects QUBINODE_VAULT_PASSWORD_FILE env var."""
        test_file = '/etc/vault/password'
        os.environ['QUBINODE_VAULT_PASSWORD_FILE'] = test_file
        
        vault_file = get_vault_password_file()
        assert vault_file == test_file
        
        # Cleanup
        os.environ.pop('QUBINODE_VAULT_PASSWORD_FILE', None)

    def test_get_pull_secret_path_default(self):
        """Test get_pull_secret_path returns ~/pull-secret.json by default."""
        os.environ.pop('QUBINODE_PULL_SECRET_PATH', None)
        
        secret_path = get_pull_secret_path()
        assert secret_path.endswith('/pull-secret.json')
        assert '~' not in secret_path  # Should be expanded

    def test_get_pull_secret_path_from_env(self):
        """Test get_pull_secret_path respects QUBINODE_PULL_SECRET_PATH env var."""
        test_path = '/opt/secrets/pull-secret.json'
        os.environ['QUBINODE_PULL_SECRET_PATH'] = test_path
        
        secret_path = get_pull_secret_path()
        assert secret_path == test_path
        
        # Cleanup
        os.environ.pop('QUBINODE_PULL_SECRET_PATH', None)


class TestSSHHelperFunctions:
    """Test SSH helper functions use configurable user."""

    def test_ssh_to_host_command_uses_config_user(self):
        """Test ssh_to_host_command uses get_ssh_user() by default."""
        os.environ['QUBINODE_SSH_USER'] = 'testuser'
        
        cmd = ssh_to_host_command("echo test")
        assert 'testuser@localhost' in cmd
        assert 'ssh' in cmd
        assert 'echo test' in cmd
        
        # Cleanup
        os.environ.pop('QUBINODE_SSH_USER', None)

    def test_ssh_to_host_command_override_user(self):
        """Test ssh_to_host_command allows user override."""
        os.environ['QUBINODE_SSH_USER'] = 'testuser'
        
        cmd = ssh_to_host_command("echo test", user="root")
        assert 'root@localhost' in cmd
        assert 'testuser' not in cmd
        
        # Cleanup
        os.environ.pop('QUBINODE_SSH_USER', None)

    def test_ssh_to_host_script_uses_config_user(self):
        """Test ssh_to_host_script uses get_ssh_user() by default."""
        os.environ['QUBINODE_SSH_USER'] = 'testuser'
        
        script = "echo line1\necho line2"
        cmd = ssh_to_host_script(script)
        assert 'testuser@localhost' in cmd
        assert 'REMOTE_SCRIPT' in cmd
        assert 'echo line1' in cmd
        
        # Cleanup
        os.environ.pop('QUBINODE_SSH_USER', None)

    def test_ssh_to_host_script_override_user(self):
        """Test ssh_to_host_script allows user override."""
        os.environ['QUBINODE_SSH_USER'] = 'testuser'
        
        script = "echo test"
        cmd = ssh_to_host_script(script, user="root")
        assert 'root@localhost' in cmd
        assert 'testuser' not in cmd
        
        # Cleanup
        os.environ.pop('QUBINODE_SSH_USER', None)


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
