"""
Tests for DAG helper functions - User configuration helpers
Tests the fix for hardcoded root user issue in DAG files.
"""

import os
import sys
import pytest
from pathlib import Path

# Add airflow/dags to path to import dag_helpers
sys.path.insert(0, str(Path(__file__).parent.parent / "airflow" / "dags"))

from dag_helpers import (
    get_ssh_user,
    get_ssh_key_path,
    get_inventory_dir,
    get_vault_password_file,
    get_pull_secret_path,
    get_kcli_pipelines_dir,
    get_openshift_agent_install_dir,
    get_config_file_path,
    get_config_check_command,
    ssh_to_host_command,
    ssh_to_host_script,
    get_ensure_vault_password_command,
    get_kcli_pipelines_vault_setup_command,
    get_vault_password_check_command,
    get_ssh_conn_id,
)


class TestUserConfigurationHelpers:
    """Test user configuration helper functions."""

    def test_get_ssh_user_default(self):
        """Test get_ssh_user returns current user by default."""
        # Clear env var if set
        os.environ.pop("QUBINODE_SSH_USER", None)

        user = get_ssh_user()
        # Should return either USER env var or 'root'
        assert user in [os.environ.get("USER", "root"), "root"]
        assert isinstance(user, str)
        assert len(user) > 0

    def test_get_ssh_user_from_env(self):
        """Test get_ssh_user respects QUBINODE_SSH_USER env var."""
        os.environ["QUBINODE_SSH_USER"] = "testuser"

        user = get_ssh_user()
        assert user == "testuser"

        # Cleanup
        os.environ.pop("QUBINODE_SSH_USER", None)

    def test_get_ssh_key_path_default(self):
        """Test get_ssh_key_path returns ~/.ssh/id_rsa by default."""
        os.environ.pop("QUBINODE_SSH_KEY_PATH", None)

        key_path = get_ssh_key_path()
        assert key_path.endswith("/.ssh/id_rsa")
        assert "~" not in key_path  # Should be expanded

    def test_get_ssh_key_path_from_env(self):
        """Test get_ssh_key_path respects QUBINODE_SSH_KEY_PATH env var."""
        test_path = "/custom/path/key.pem"
        os.environ["QUBINODE_SSH_KEY_PATH"] = test_path

        key_path = get_ssh_key_path()
        assert key_path == test_path

        # Cleanup
        os.environ.pop("QUBINODE_SSH_KEY_PATH", None)

    def test_get_inventory_dir_default(self):
        """Test get_inventory_dir returns ~/.generated by default."""
        os.environ.pop("QUBINODE_INVENTORY_DIR", None)

        inv_dir = get_inventory_dir()
        assert inv_dir.endswith("/.generated")
        assert "~" not in inv_dir  # Should be expanded

    def test_get_inventory_dir_from_env(self):
        """Test get_inventory_dir respects QUBINODE_INVENTORY_DIR env var."""
        test_dir = "/opt/inventories"
        os.environ["QUBINODE_INVENTORY_DIR"] = test_dir

        inv_dir = get_inventory_dir()
        assert inv_dir == test_dir

        # Cleanup
        os.environ.pop("QUBINODE_INVENTORY_DIR", None)

    def test_get_vault_password_file_default(self):
        """Test get_vault_password_file returns ~/.vault_password by default."""
        os.environ.pop("QUBINODE_VAULT_PASSWORD_FILE", None)

        vault_file = get_vault_password_file()
        assert vault_file.endswith("/.vault_password")
        assert "~" not in vault_file  # Should be expanded

    def test_get_vault_password_file_from_env(self):
        """Test get_vault_password_file respects QUBINODE_VAULT_PASSWORD_FILE env var."""
        test_file = "/etc/vault/password"
        os.environ["QUBINODE_VAULT_PASSWORD_FILE"] = test_file

        vault_file = get_vault_password_file()
        assert vault_file == test_file

        # Cleanup
        os.environ.pop("QUBINODE_VAULT_PASSWORD_FILE", None)

    def test_get_pull_secret_path_default(self):
        """Test get_pull_secret_path returns ~/pull-secret.json by default."""
        os.environ.pop("QUBINODE_PULL_SECRET_PATH", None)

        secret_path = get_pull_secret_path()
        assert secret_path.endswith("/pull-secret.json")
        assert "~" not in secret_path  # Should be expanded

    def test_get_pull_secret_path_from_env(self):
        """Test get_pull_secret_path respects QUBINODE_PULL_SECRET_PATH env var."""
        test_path = "/opt/secrets/pull-secret.json"
        os.environ["QUBINODE_PULL_SECRET_PATH"] = test_path

        secret_path = get_pull_secret_path()
        assert secret_path == test_path

        # Cleanup
        os.environ.pop("QUBINODE_PULL_SECRET_PATH", None)


class TestSSHHelperFunctions:
    """Test SSH helper functions use configurable user."""

    def test_ssh_to_host_command_uses_config_user(self):
        """Test ssh_to_host_command uses get_ssh_user() by default."""
        os.environ["QUBINODE_SSH_USER"] = "testuser"

        cmd = ssh_to_host_command("echo test")
        assert "testuser@localhost" in cmd
        assert "ssh" in cmd
        assert "echo test" in cmd

        # Cleanup
        os.environ.pop("QUBINODE_SSH_USER", None)

    def test_ssh_to_host_command_override_user(self):
        """Test ssh_to_host_command allows user override."""
        os.environ["QUBINODE_SSH_USER"] = "testuser"

        cmd = ssh_to_host_command("echo test", user="root")
        assert "root@localhost" in cmd
        assert "testuser" not in cmd

        # Cleanup
        os.environ.pop("QUBINODE_SSH_USER", None)

    def test_ssh_to_host_script_uses_config_user(self):
        """Test ssh_to_host_script uses get_ssh_user() by default."""
        os.environ["QUBINODE_SSH_USER"] = "testuser"

        script = "echo line1\necho line2"
        cmd = ssh_to_host_script(script)
        assert "testuser@localhost" in cmd
        assert "REMOTE_SCRIPT" in cmd
        assert "echo line1" in cmd

        # Cleanup
        os.environ.pop("QUBINODE_SSH_USER", None)

    def test_ssh_to_host_script_override_user(self):
        """Test ssh_to_host_script allows user override."""
        os.environ["QUBINODE_SSH_USER"] = "testuser"

        script = "echo test"
        cmd = ssh_to_host_script(script, user="root")
        assert "root@localhost" in cmd
        assert "testuser" not in cmd

        # Cleanup
        os.environ.pop("QUBINODE_SSH_USER", None)


class TestKcliPipelinesDir:
    """Test kcli-pipelines directory helper."""

    def test_get_kcli_pipelines_dir_default(self):
        """Test get_kcli_pipelines_dir returns /opt/kcli-pipelines by default."""
        os.environ.pop("KCLI_PIPELINES_DIR", None)

        pipelines_dir = get_kcli_pipelines_dir()
        assert pipelines_dir == "/opt/kcli-pipelines"

    def test_get_kcli_pipelines_dir_from_env(self):
        """Test get_kcli_pipelines_dir respects KCLI_PIPELINES_DIR env var."""
        test_dir = "/custom/kcli-pipelines"
        os.environ["KCLI_PIPELINES_DIR"] = test_dir

        pipelines_dir = get_kcli_pipelines_dir()
        assert pipelines_dir == test_dir

        # Cleanup
        os.environ.pop("KCLI_PIPELINES_DIR", None)


class TestConfigPathHelpers:
    """Test configuration path helper functions (Issue #124)."""

    def test_get_openshift_agent_install_dir_default(self):
        """Test get_openshift_agent_install_dir returns container path by default."""
        os.environ.pop("OPENSHIFT_AGENT_INSTALL_DIR", None)

        # Should return container mount point if home path doesn't exist
        agent_dir = get_openshift_agent_install_dir()
        # Will return /opt/openshift-agent-install or home path depending on existence
        assert "openshift-agent-install" in agent_dir

    def test_get_openshift_agent_install_dir_from_env(self):
        """Test get_openshift_agent_install_dir respects env var."""
        # Create a temp directory for testing
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            os.environ["OPENSHIFT_AGENT_INSTALL_DIR"] = tmpdir

            agent_dir = get_openshift_agent_install_dir()
            assert agent_dir == tmpdir

        # Cleanup
        os.environ.pop("OPENSHIFT_AGENT_INSTALL_DIR", None)

    def test_get_config_file_path_not_found(self):
        """Test get_config_file_path raises FileNotFoundError when not found."""
        with pytest.raises(FileNotFoundError) as exc_info:
            get_config_file_path("nonexistent/file/path.yml")

        assert "Configuration file not found" in str(exc_info.value)
        assert "config-sync.sh" in str(exc_info.value)

    def test_get_config_file_path_found(self):
        """Test get_config_file_path finds existing file."""
        import tempfile

        with tempfile.TemporaryDirectory() as tmpdir:
            # Create a test file
            test_file = os.path.join(tmpdir, "test.yml")
            with open(test_file, "w") as f:
                f.write("test: true")

            # Search with tmpdir as search path
            found_path = get_config_file_path("test.yml", search_paths=[tmpdir])
            assert found_path == test_file

    def test_get_config_check_command_generates_bash(self):
        """Test get_config_check_command generates valid bash."""
        paths = ["/opt/test/file1.yml", "/opt/test/file2.env"]
        cmd = get_config_check_command(paths)

        assert "Checking Configuration File Access" in cmd
        assert "/opt/test/file1.yml" in cmd
        assert "/opt/test/file2.env" in cmd
        assert "[OK]" in cmd
        assert "[ERROR]" in cmd

    def test_get_config_check_command_custom_error(self):
        """Test get_config_check_command with custom error message."""
        paths = ["/opt/test.yml"]
        custom_error = "Custom error message for testing"
        cmd = get_config_check_command(paths, error_message=custom_error)

        assert custom_error in cmd


class TestVaultPasswordHelpers:
    """Test vault password management helper functions (Issue #123)."""

    def test_get_ensure_vault_password_command_default_path(self):
        """Test get_ensure_vault_password_command uses default vault path."""
        os.environ.pop("QUBINODE_VAULT_PASSWORD_FILE", None)

        cmd = get_ensure_vault_password_command()

        # Should contain expected vault password path (expanded home)
        assert "/.vault_password" in cmd
        assert "Ensuring Vault Password File Exists" in cmd
        assert "[OK]" in cmd
        assert "chmod 600" in cmd

    def test_get_ensure_vault_password_command_custom_path(self):
        """Test get_ensure_vault_password_command with custom path."""
        custom_path = "/custom/vault/password"

        cmd = get_ensure_vault_password_command(vault_password_file=custom_path)

        assert custom_path in cmd
        assert "VAULT_FILE=" in cmd

    def test_get_ensure_vault_password_command_custom_variable(self):
        """Test get_ensure_vault_password_command with custom Airflow variable."""
        cmd = get_ensure_vault_password_command(default_password_var="CUSTOM_VAR")

        assert "CUSTOM_VAR" in cmd
        assert "airflow variables get CUSTOM_VAR" in cmd

    def test_get_ensure_vault_password_command_no_create(self):
        """Test get_ensure_vault_password_command with create_if_missing=False."""
        cmd = get_ensure_vault_password_command(create_if_missing=False)

        assert 'CREATE_IF_MISSING="false"' in cmd

    def test_get_kcli_pipelines_vault_setup_command_default(self):
        """Test get_kcli_pipelines_vault_setup_command with defaults."""
        os.environ.pop("QUBINODE_VAULT_PASSWORD_FILE", None)
        os.environ.pop("KCLI_PIPELINES_DIR", None)

        cmd = get_kcli_pipelines_vault_setup_command()

        # Should contain default pipelines directory
        assert "/opt/kcli-pipelines" in cmd
        assert "Setting Up Vault Password for kcli-pipelines" in cmd
        # Should include default components
        assert "vyos-router" in cmd
        assert "step-ca-server" in cmd
        assert "ln -s" in cmd  # Creates symlinks

    def test_get_kcli_pipelines_vault_setup_command_specific_components(self):
        """Test get_kcli_pipelines_vault_setup_command with specific components."""
        components = ["vyos-router", "freeipa-workshop-deployer"]

        cmd = get_kcli_pipelines_vault_setup_command(components=components)

        assert "vyos-router" in cmd
        assert "freeipa-workshop-deployer" in cmd
        # Should not contain components not in list
        assert "COMPONENTS=" in cmd

    def test_get_kcli_pipelines_vault_setup_command_custom_paths(self):
        """Test get_kcli_pipelines_vault_setup_command with custom paths."""
        custom_vault = "/custom/vault"
        custom_pipelines = "/custom/pipelines"

        cmd = get_kcli_pipelines_vault_setup_command(
            vault_password_file=custom_vault,
            pipelines_dir=custom_pipelines,
        )

        assert custom_vault in cmd
        assert custom_pipelines in cmd

    def test_get_vault_password_check_command_default(self):
        """Test get_vault_password_check_command with defaults."""
        os.environ.pop("QUBINODE_VAULT_PASSWORD_FILE", None)

        cmd = get_vault_password_check_command()

        assert "/.vault_password" in cmd
        assert "Checking vault password file" in cmd
        assert "[OK]" in cmd
        assert "[ERROR]" in cmd
        assert "exit 1" in cmd  # Should fail if missing by default

    def test_get_vault_password_check_command_no_fail(self):
        """Test get_vault_password_check_command with fail_if_missing=False."""
        cmd = get_vault_password_check_command(fail_if_missing=False)

        assert "[WARN] Continuing without vault password" in cmd
        # Should not exit 1
        assert "exit 1" not in cmd.split("[WARN]")[1]

    def test_get_vault_password_check_command_custom_path(self):
        """Test get_vault_password_check_command with custom path."""
        custom_path = "/etc/ansible/vault"

        cmd = get_vault_password_check_command(vault_password_file=custom_path)

        assert custom_path in cmd
        assert f'VAULT_FILE="{custom_path}"' in cmd


class TestSSHOperatorHelpers:
    """Test SSHOperator helper functions (Issue: Replace manual SSH)."""

    def test_get_ssh_conn_id_default(self):
        """Test get_ssh_conn_id returns default connection ID."""
        os.environ.pop("QUBINODE_SSH_CONN_ID", None)

        conn_id = get_ssh_conn_id()
        assert conn_id == "localhost_ssh"

    def test_get_ssh_conn_id_from_env(self):
        """Test get_ssh_conn_id respects QUBINODE_SSH_CONN_ID env var."""
        test_conn_id = "custom_ssh_connection"
        os.environ["QUBINODE_SSH_CONN_ID"] = test_conn_id

        conn_id = get_ssh_conn_id()
        assert conn_id == test_conn_id

        # Cleanup
        os.environ.pop("QUBINODE_SSH_CONN_ID", None)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
