# Description: Gitlab CI/CD pipeline for FreeIPA
# SSH_USER SSH_PASSWORD SSH_HOST will be passed through the pipeline
stages:
  - freeipa

build:
  stage: freeipa
  image: fedora:37
  variables:
    CICD_PIPELINE: "true"
  script:
    - dnf install wget openssh-clients sshpass -y
    - mkdir -p ~/.ssh/
    - ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    - sshpass -p "$SSH_PASSWORD" ssh-copy-id -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST"
    - ssh "$SSH_USER"@"$SSH_HOST"  'env CICD_PIPELINE="'$CICD_PIPELINE'" && source ~/.bash_aliases && freeipa-utils deploy'
  only:
    - main
