# Description: Gitlab CI/CD pipeline for FreeIPA
# SSH_USER SSH_PASSWORD SSH_HOST will be passed through the pipeline
stages:
  - freeipa

build:
  stage: freeipa
  image: fedora:37
  variables:
    CICD_PIPELINE: "true"
  allow_failure: false
  script:
    - dnf install wget openssh-clients sshpass -y
    - mkdir -p ~/.ssh/
    - ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
    - sshpass -p "$SSH_PASSWORD" ssh-copy-id -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST"
    - | 
      if [ "$ROCKY" = "true" ]; then
        ssh "$SSH_USER"@"$SSH_HOST" "sudo -E env CICD_PIPELINE=\"$CICD_PIPELINE\"   INVENTORY=\"$INVENTORY\" bash -s -- <  /opt/qubinode_navigator/rocky-linux-hypervisor.sh --deploy-freeipa"
      elif [ "$ROCKY" = "false" ]; then
        ssh "$SSH_USER"@"$SSH_HOST" 'env CICD_PIPELINE="'$CICD_PIPELINE'"  INVENTORY="'$INVENTORY'"  && source ~/.bash_aliases && freeipa-utils deploy'
      fi
  only:
    - main