---
# https://github.com/tosin2013/kcli-openshift4-baremetal/blob/master/paramfiles/lab.yml
# https://github.com/tosin2013/kcli-openshift4-baremetal/blob/master/plans/kcli_plan_default.yml
# Use n2.xlarge.x86 on Equinix
lab: true
version: stable
tag: "4.14"
virtual_protocol: redfish
virtual_ctlplanes: true
launch_steps: true
deploy_openshift: true
installer_wait: true
cluster: lab
domain: example.com
baremetal_cidr: 192.168.130.0/24
baremetal_net: lab-baremetal
disk_size: 120
virtual_ctlplanes_memory: 32768
virtual_ctlplanes_numcpus: 8
virtual_workers: false
extra_disks:
- size: 400
api_ip: 192.168.130.253
ingress_ip: 192.168.130.252
baremetal_ips:
- 192.168.130.20
- 192.168.130.21
- 192.168.130.22
baremetal_macs:
- aa:aa:aa:aa:bb:01
- aa:aa:aa:aa:bb:02
- aa:aa:aa:aa:bb:03
notify: true
nfs: false
disconnected: false