---
# https://github.com/tosin2013/kcli-openshift4-baremetal/blob/master/paramfiles/lab.yml
lab: true
version: stable
tag: "4.13"
virtual_protocol: redfish
virtual_ctlplanes: true
launch_steps: true
deploy_openshift: true
installer_wait: false
cluster: lab
domain: karmalabs.corp
baremetal_cidr: 192.168.130.0/24
baremetal_net: lab-baremetal
virtual_ctlplanes_memory: 16384
virtual_ctlplanes_numcpus: 8
virtual_workers: true
virtual_workers_memory: 16384
virtual_workers_number: 3
virtual_workers_numcpus: 8
virtual_workers_disksize: 120
extra_disks:
- size: 300
api_ip: 192.168.130.253
ingress_ip: 192.168.130.252
baremetal_ips:
- 192.168.130.20
- 192.168.130.21
- 192.168.130.22
- 192.168.130.23
- 192.168.130.24
- 192.168.130.25
baremetal_macs:
- aa:aa:aa:aa:bb:01
- aa:aa:aa:aa:bb:02
- aa:aa:aa:aa:bb:03
- aa:aa:aa:aa:bb:04
- aa:aa:aa:aa:bb:05
- aa:aa:aa:aa:bb:06
notify: true
nfs: true
disconnected: false