#!/bin/bash
# =============================================================================
# Configuration Sync Tool for Airflow Containers
# =============================================================================
# This script manages configuration file synchronization and volume mounts
# for Airflow containers, solving the problem where user home directories
# are not accessible inside containers.
#
# Usage:
#   ./config-sync.sh generate    # Generate docker-compose.override.yml
#   ./config-sync.sh discover    # Auto-discover config directories
#   ./config-sync.sh validate    # Validate current mounts
#   ./config-sync.sh sync        # One-time sync of config files
#   ./config-sync.sh watch       # Watch mode for continuous sync
#
# See: Issue #124 - Configuration File Sync Mechanism
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AIRFLOW_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="${AIRFLOW_DIR}/config/volume-mounts.yml"
OVERRIDE_FILE="${AIRFLOW_DIR}/docker-compose.override.yml"

# Check for required tools
check_requirements() {
    local missing=()

    if ! command -v yq &> /dev/null; then
        missing+=("yq")
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        log_warning "Optional tools not found: ${missing[*]}"
        log_info "Install with: pip3 install yq"
        log_info "Falling back to basic parsing..."
        return 1
    fi
    return 0
}

# Parse volume mounts from YAML (basic parsing without yq)
parse_mounts_basic() {
    local yaml_file="$1"
    local section="$2"

    # Basic YAML parsing for simple structure
    awk -v section="$section" '
    BEGIN { in_section = 0; in_item = 0 }
    /^[a-z_]+:/ {
        if ($1 == section":") { in_section = 1 }
        else { in_section = 0 }
    }
    in_section && /^  - source:/ {
        gsub(/^  - source: ["'\'']?/, "")
        gsub(/["'\'']?$/, "")
        source = $0
    }
    in_section && /^    target:/ {
        gsub(/^    target: ["'\'']?/, "")
        gsub(/["'\'']?$/, "")
        target = $0
    }
    in_section && /^    mode:/ {
        gsub(/^    mode: ["'\'']?/, "")
        gsub(/["'\'']?$/, "")
        mode = $0
        # Output when we have all three
        if (source && target) {
            print source ":" target ":" (mode ? mode : "ro")
            source = ""; target = ""; mode = ""
        }
    }
    ' "$yaml_file"
}

# Expand environment variables in path
expand_path() {
    local path="$1"
    # Expand ${HOME}, ${USER}, ~, etc.
    path="${path//\$\{HOME\}/$HOME}"
    path="${path//\$HOME/$HOME}"
    path="${path//\~/$HOME}"
    path="${path//\$\{USER\}/$USER}"
    path="${path//\$USER/$USER}"
    echo "$path"
}

# Generate docker-compose.override.yml
generate_override() {
    log_info "Generating docker-compose.override.yml..."

    if [[ ! -f "$CONFIG_FILE" ]]; then
        log_error "Config file not found: $CONFIG_FILE"
        return 1
    fi

    # Start the override file
    cat > "$OVERRIDE_FILE" << 'HEADER'
# =============================================================================
# Docker Compose Override - Auto-generated by config-sync.sh
# =============================================================================
# This file adds additional volume mounts for user configuration files.
# DO NOT EDIT MANUALLY - regenerate with: ./scripts/config-sync.sh generate
#
# To add custom mounts, edit: config/volume-mounts.yml
# =============================================================================

version: '3.8'

x-extra-volumes:
  &extra-volumes
HEADER

    # Parse and add mounts
    local mount_count=0
    local mounts=""

    # Parse default_mounts
    while IFS=: read -r source target mode; do
        [[ -z "$source" ]] && continue

        source=$(expand_path "$source")
        mode="${mode:-ro}"

        # Check if source exists
        if [[ -d "$source" ]]; then
            mounts+="    - ${source}:${target}:${mode}\n"
            log_success "Mount: $source -> $target ($mode)"
            ((mount_count++))
        else
            log_warning "Skipping (not found): $source"
        fi
    done < <(parse_mounts_basic "$CONFIG_FILE" "default_mounts")

    # Parse custom_mounts
    while IFS=: read -r source target mode; do
        [[ -z "$source" ]] && continue

        source=$(expand_path "$source")
        mode="${mode:-ro}"

        if [[ -d "$source" ]]; then
            mounts+="    - ${source}:${target}:${mode}\n"
            log_success "Mount: $source -> $target ($mode)"
            ((mount_count++))
        else
            log_warning "Skipping (not found): $source"
        fi
    done < <(parse_mounts_basic "$CONFIG_FILE" "custom_mounts")

    # Write mounts to override file
    if [[ $mount_count -gt 0 ]]; then
        echo -e "$mounts" >> "$OVERRIDE_FILE"

        # Add services that use these volumes
        cat >> "$OVERRIDE_FILE" << 'SERVICES'

services:
  airflow-webserver:
    volumes:
      <<: *extra-volumes

  airflow-scheduler:
    volumes:
      <<: *extra-volumes

  airflow-mcp-server:
    volumes:
      <<: *extra-volumes
SERVICES

        log_success "Generated $OVERRIDE_FILE with $mount_count mounts"
        echo ""
        log_info "To apply changes, restart Airflow:"
        echo "  cd $AIRFLOW_DIR && podman-compose down && podman-compose up -d"
    else
        log_warning "No valid mounts found"
        rm -f "$OVERRIDE_FILE"
    fi
}

# Auto-discover configuration directories
discover_configs() {
    log_info "Discovering configuration directories..."
    echo ""

    local found=()

    # Common config directory patterns
    local patterns=(
        "$HOME/openshift-agent-install"
        "$HOME/openshift-install"
        "$HOME/.generated"
        "$HOME/kcli-pipelines"
        "$HOME/cluster-configs"
        "/opt/kcli-pipelines"
        "/opt/openshift-agent-install"
    )

    # Check each pattern
    for pattern in "${patterns[@]}"; do
        if [[ -d "$pattern" ]]; then
            found+=("$pattern")
            echo -e "  ${GREEN}✓${NC} Found: $pattern"
        fi
    done

    # Search for marker files in home directories
    log_info "Searching for configuration marker files..."
    local marker_files=("cluster.yml" "install-config.yaml" "agent-config.yaml")

    for marker in "${marker_files[@]}"; do
        while IFS= read -r -d '' file; do
            local dir=$(dirname "$file")
            if [[ ! " ${found[*]} " =~ " ${dir} " ]]; then
                found+=("$dir")
                echo -e "  ${GREEN}✓${NC} Found (by $marker): $dir"
            fi
        done < <(find "$HOME" -maxdepth 4 -name "$marker" -print0 2>/dev/null)
    done

    echo ""
    if [[ ${#found[@]} -gt 0 ]]; then
        log_success "Found ${#found[@]} configuration directories"
        echo ""
        log_info "To add these to volume mounts, edit:"
        echo "  $CONFIG_FILE"
        echo ""
        log_info "Example entries to add under 'custom_mounts:':"
        echo ""
        for dir in "${found[@]}"; do
            local target="/opt/$(basename "$dir")"
            echo "  - source: \"$dir\""
            echo "    target: \"$target\""
            echo "    mode: \"ro\""
            echo "    description: \"Auto-discovered config\""
            echo ""
        done
    else
        log_warning "No configuration directories found"
    fi
}

# Validate current mounts
validate_mounts() {
    log_info "Validating volume mounts..."
    echo ""

    local errors=0

    # Check if override file exists
    if [[ -f "$OVERRIDE_FILE" ]]; then
        log_success "Override file exists: $OVERRIDE_FILE"
    else
        log_warning "No override file found"
        log_info "Run: $0 generate"
    fi

    # Check default mounts from docker-compose.yml
    log_info "Checking docker-compose.yml mounts..."
    local compose_file="${AIRFLOW_DIR}/docker-compose.yml"

    if [[ -f "$compose_file" ]]; then
        # Extract volume mounts and check if source exists
        grep -E "^\s+-\s+[/~]" "$compose_file" | while read -r line; do
            # Extract source path (before the first :)
            local source=$(echo "$line" | sed 's/.*- //' | cut -d: -f1)
            source=$(expand_path "$source")

            if [[ -e "$source" ]]; then
                echo -e "  ${GREEN}✓${NC} $source"
            else
                echo -e "  ${YELLOW}⚠${NC} $source (not found)"
                ((errors++)) || true
            fi
        done
    fi

    echo ""
    if [[ $errors -eq 0 ]]; then
        log_success "All mounts validated"
    else
        log_warning "Some mounts have issues"
    fi
}

# One-time sync of config files
sync_configs() {
    log_info "Syncing configuration files..."

    # This is a placeholder for actual sync logic
    # In practice, volume mounts handle this automatically
    # This function could be used for copying files to a shared location

    log_warning "Direct file sync not implemented"
    log_info "Use volume mounts instead (run: $0 generate)"
}

# Watch mode for continuous sync
watch_configs() {
    log_info "Watch mode not yet implemented"
    log_info "Use volume mounts for automatic file access"
}

# Show usage
show_usage() {
    echo "Configuration Sync Tool for Airflow Containers"
    echo ""
    echo "Usage: $0 <command>"
    echo ""
    echo "Commands:"
    echo "  generate    Generate docker-compose.override.yml from volume-mounts.yml"
    echo "  discover    Auto-discover configuration directories"
    echo "  validate    Validate current volume mounts"
    echo "  sync        One-time sync of config files"
    echo "  watch       Watch mode for continuous sync (not implemented)"
    echo "  help        Show this help message"
    echo ""
    echo "Configuration:"
    echo "  Volume mounts: $CONFIG_FILE"
    echo "  Override file: $OVERRIDE_FILE"
    echo ""
    echo "Examples:"
    echo "  $0 discover           # Find config directories"
    echo "  $0 generate           # Create docker-compose.override.yml"
    echo "  $0 validate           # Check mount status"
    echo ""
}

# Main
main() {
    local command="${1:-help}"

    case "$command" in
        generate)
            generate_override
            ;;
        discover)
            discover_configs
            ;;
        validate)
            validate_mounts
            ;;
        sync)
            sync_configs
            ;;
        watch)
            watch_configs
            ;;
        help|--help|-h)
            show_usage
            ;;
        *)
            log_error "Unknown command: $command"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
