#!/bin/bash
# ADR-0049: Generate OpenLineage facets for DAG files
# This script populates the .OpenLineage.job.facets.json template with actual values
#
# Usage:
#   ./generate-lineage-facets.sh [dag_file]
#   ./generate-lineage-facets.sh  # Process all DAGs
#
# The script extracts git information and DAG metadata to create
# code lineage facets that link DAG executions to their source code.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAGS_DIR="${SCRIPT_DIR}/../dags"
TEMPLATE_FILE="${DAGS_DIR}/.OpenLineage.job.facets.json"
OUTPUT_DIR="${DAGS_DIR}/.lineage"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get git information
get_git_info() {
    local file="$1"

    # Get current branch
    GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

    # Get current commit SHA
    GIT_COMMIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "unknown")

    # Get commit message (first line)
    GIT_COMMIT_MESSAGE=$(git log -1 --format=%s 2>/dev/null || echo "unknown")

    # Get commit author
    GIT_AUTHOR=$(git log -1 --format='%an <%ae>' 2>/dev/null || echo "unknown")

    # Get commit timestamp
    GIT_COMMIT_TIMESTAMP=$(git log -1 --format=%cI 2>/dev/null || echo "unknown")

    # Get current tag if any
    GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")

    # Get file-specific last commit
    if [ -n "$file" ] && [ -f "$file" ]; then
        DAG_FILE_COMMIT=$(git log -1 --format=%H -- "$file" 2>/dev/null || echo "$GIT_COMMIT_SHA")
    else
        DAG_FILE_COMMIT="$GIT_COMMIT_SHA"
    fi
}

# Get DAG metadata from Python file
get_dag_metadata() {
    local file="$1"

    # Extract DAG docstring (first triple-quoted string)
    DAG_DESCRIPTION=$(python3 -c "
import ast
import sys
try:
    with open('$file', 'r') as f:
        tree = ast.parse(f.read())
    for node in ast.walk(tree):
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            if isinstance(node.value.value, str) and len(node.value.value) > 10:
                print(node.value.value.split('\n')[0][:200])
                break
except:
    pass
" 2>/dev/null || echo "No description")

    # Extract owner from DAG definition
    DAG_OWNER=$(grep -oP "owner\s*=\s*['\"]([^'\"]+)['\"]" "$file" 2>/dev/null | head -1 | sed "s/.*['\"]\\([^'\"]*\\)['\"].*/\\1/" || echo "qubinode-team")

    # Calculate file checksum
    DAG_FILE_CHECKSUM=$(sha256sum "$file" 2>/dev/null | cut -d' ' -f1 || echo "unknown")
}

# Generate facets for a single DAG file
generate_facets() {
    local dag_file="$1"
    local dag_name
    dag_name=$(basename "$dag_file" .py)

    log_info "Processing: $dag_name"

    # Get git and DAG metadata
    get_git_info "$dag_file"
    get_dag_metadata "$dag_file"

    # Environment info
    ENVIRONMENT_TYPE="${QUBINODE_ENVIRONMENT:-development}"
    AIRFLOW_VERSION=$(python3 -c "import airflow; print(airflow.__version__)" 2>/dev/null || echo "2.10.4")
    PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2 || echo "3.12")
    QUBINODE_VERSION="1.0.0"

    # Find related ADRs (grep for ADR references in the file)
    RELATED_ADRS=$(grep -oE 'ADR-[0-9]+' "$dag_file" 2>/dev/null | sort -u | tr '\n' ',' | sed 's/,$//' || echo "")

    # Create output directory
    mkdir -p "$OUTPUT_DIR"

    # Generate facets JSON
    local output_file="${OUTPUT_DIR}/${dag_name}.facets.json"

    cat > "$output_file" << EOF
{
  "_comment": "Auto-generated by generate-lineage-facets.sh",
  "_generated_at": "$(date -Iseconds)",
  "_dag_file": "$dag_file",

  "codeLineage": {
    "_producer": "qubinode-navigator",
    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/CodeLineageFacet.json",
    "gitRepository": "https://github.com/qubinode/qubinode_navigator",
    "gitBranch": "$GIT_BRANCH",
    "gitCommit": "$GIT_COMMIT_SHA",
    "gitCommitMessage": $(echo "$GIT_COMMIT_MESSAGE" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read().strip()))'),
    "gitAuthor": "$GIT_AUTHOR",
    "gitCommitTimestamp": "$GIT_COMMIT_TIMESTAMP",
    "dagFileCommit": "$DAG_FILE_COMMIT",
    "dagFilePath": "airflow/dags/$dag_name.py",
    "dagFileChecksum": "$DAG_FILE_CHECKSUM"
  },

  "sourceCode": {
    "_producer": "qubinode-navigator",
    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SourceCodeFacet.json",
    "language": "python",
    "sourceCodeLocation": {
      "type": "git",
      "url": "https://github.com/qubinode/qubinode_navigator",
      "path": "airflow/dags/$dag_name.py",
      "version": "$GIT_COMMIT_SHA",
      "tag": "$GIT_TAG",
      "branch": "$GIT_BRANCH"
    }
  },

  "environment": {
    "_producer": "qubinode-navigator",
    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/EnvironmentFacet.json",
    "environmentType": "$ENVIRONMENT_TYPE",
    "airflowVersion": "$AIRFLOW_VERSION",
    "pythonVersion": "$PYTHON_VERSION",
    "qubinodeVersion": "$QUBINODE_VERSION"
  },

  "documentation": {
    "_producer": "qubinode-navigator",
    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DocumentationFacet.json",
    "description": $(echo "$DAG_DESCRIPTION" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read().strip()))'),
    "relatedADRs": "$RELATED_ADRS",
    "runbook": ""
  },

  "ownership": {
    "_producer": "qubinode-navigator",
    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/OwnershipFacet.json",
    "owners": [
      {
        "name": "$DAG_OWNER",
        "type": "MAINTAINER"
      }
    ]
  }
}
EOF

    log_info "  Generated: $output_file"
}

# Main function
main() {
    log_info "OpenLineage Facet Generator for Qubinode Navigator"
    log_info "=================================================="

    # Check if we're in a git repository
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        log_warn "Not in a git repository - git metadata will be limited"
    fi

    # Process specific file or all DAGs
    if [ $# -gt 0 ]; then
        # Process specific file
        if [ -f "$1" ]; then
            generate_facets "$1"
        else
            log_error "File not found: $1"
            exit 1
        fi
    else
        # Process all Python files in dags directory
        local count=0
        for dag_file in "$DAGS_DIR"/*.py; do
            if [ -f "$dag_file" ]; then
                # Skip __init__.py and other non-DAG files
                case "$(basename "$dag_file")" in
                    __init__.py|__pycache__) continue ;;
                esac
                generate_facets "$dag_file"
                ((count++))
            fi
        done

        log_info "=================================================="
        log_info "Processed $count DAG files"
        log_info "Facets written to: $OUTPUT_DIR"
    fi
}

main "$@"
