#!/bin/bash
# =============================================================================
# Initialize Prerequisites for Infrastructure DAGs
# =============================================================================
# Issue #3 Fix: Auto-configure prerequisites for "just works" experience
#
# This script creates:
# 1. vault.yml with default credentials (if missing)
# 2. Clones freeipa-workshop-deployer (if missing)
# 3. Clones kcli-pipelines (if missing)
# 4. Configures SSH keys for container-to-host communication
#
# Usage: ./init-prerequisites.sh
# =============================================================================

set -euo pipefail

echo "========================================"
echo "Initializing Infrastructure Prerequisites"
echo "========================================"
echo ""

# Configuration
QUBINODE_DIR="${QUBINODE_DIR:-/opt/qubinode_navigator}"
VAULT_FILE="$QUBINODE_DIR/inventories/localhost/group_vars/control/vault.yml"
FREEIPA_DIR="/opt/freeipa-workshop-deployer"
KCLI_PIPELINES_DIR="/opt/kcli-pipelines"

ERRORS=0
WARNINGS=0

# =============================================================================
# 1. Create vault.yml if missing
# =============================================================================
echo "[INFO] Checking vault.yml..."

if [ -f "$VAULT_FILE" ]; then
    echo "[OK] vault.yml exists at $VAULT_FILE"
else
    echo "[INFO] Creating default vault.yml..."

    # Create directory if needed
    mkdir -p "$(dirname "$VAULT_FILE")"

    # Generate random passwords for security
    FREEIPA_PASS=$(openssl rand -base64 12 | tr -d '/+=' | head -c 16)
    STEPCA_PASS=$(openssl rand -base64 12 | tr -d '/+=' | head -c 16)

    cat > "$VAULT_FILE" << EOF
---
# Qubinode Navigator - Default Credentials
# Auto-generated by init-prerequisites.sh
# Generated: $(date -Iseconds)
#
# IMPORTANT: Change these passwords in production!
# These are default development credentials.

# FreeIPA Server Credentials
freeipa_server_admin_password: "${FREEIPA_PASS}!"
freeipa_server_dm_password: "${FREEIPA_PASS}!"

# Step-CA Certificate Authority Credentials
stepca_password: "${STEPCA_PASS}!"

# VyOS Router Credentials
vyos_password: "vyos"

# Harbor Registry Credentials
harbor_admin_password: "Harbor12345"

# OpenShift Pull Secret Path
# Uncomment and update with your pull secret location
# pull_secret: "/root/pull-secret.json"

# Red Hat Subscription (for RHEL systems)
# rhsm_username: "your-username"
# rhsm_password: "your-password"
# rhsm_pool_id: "your-pool-id"
EOF

    chmod 600 "$VAULT_FILE"
    echo "[OK] vault.yml created at $VAULT_FILE"
    echo "[WARN] Default passwords generated - change in production!"
    WARNINGS=$((WARNINGS + 1))
fi

# =============================================================================
# 2. Clone freeipa-workshop-deployer if missing
# =============================================================================
echo ""
echo "[INFO] Checking freeipa-workshop-deployer..."

if [ -d "$FREEIPA_DIR" ]; then
    echo "[OK] freeipa-workshop-deployer exists at $FREEIPA_DIR"
else
    echo "[INFO] Cloning freeipa-workshop-deployer..."

    if git clone https://github.com/tosin2013/freeipa-workshop-deployer.git "$FREEIPA_DIR" 2>/dev/null; then
        echo "[OK] freeipa-workshop-deployer cloned to $FREEIPA_DIR"
    else
        echo "[ERROR] Failed to clone freeipa-workshop-deployer"
        echo "  Try manually: git clone https://github.com/tosin2013/freeipa-workshop-deployer.git $FREEIPA_DIR"
        ERRORS=$((ERRORS + 1))
    fi
fi

# Create symlink in home directory if needed
if [ ! -e "/root/freeipa-workshop-deployer" ] && [ -d "$FREEIPA_DIR" ]; then
    ln -sf "$FREEIPA_DIR" /root/freeipa-workshop-deployer
    echo "[OK] Created symlink /root/freeipa-workshop-deployer -> $FREEIPA_DIR"
fi

# =============================================================================
# 3. Clone kcli-pipelines if missing
# =============================================================================
echo ""
echo "[INFO] Checking kcli-pipelines..."

if [ -d "$KCLI_PIPELINES_DIR" ]; then
    echo "[OK] kcli-pipelines exists at $KCLI_PIPELINES_DIR"
else
    echo "[INFO] Cloning kcli-pipelines..."

    if git clone https://github.com/tosin2013/kcli-pipelines.git "$KCLI_PIPELINES_DIR" 2>/dev/null; then
        echo "[OK] kcli-pipelines cloned to $KCLI_PIPELINES_DIR"
    else
        echo "[ERROR] Failed to clone kcli-pipelines"
        echo "  Try manually: git clone https://github.com/tosin2013/kcli-pipelines.git $KCLI_PIPELINES_DIR"
        ERRORS=$((ERRORS + 1))
    fi
fi

# Create symlink in home directory if needed
if [ ! -e "/root/kcli-pipelines" ] && [ -d "$KCLI_PIPELINES_DIR" ]; then
    ln -sf "$KCLI_PIPELINES_DIR" /root/kcli-pipelines
    echo "[OK] Created symlink /root/kcli-pipelines -> $KCLI_PIPELINES_DIR"
fi

# =============================================================================
# 4. Configure SSH keys for container-to-host communication
# =============================================================================
echo ""
echo "[INFO] Checking SSH configuration..."

SSH_KEY="/root/.ssh/id_rsa"
AUTHORIZED_KEYS="/root/.ssh/authorized_keys"

# Ensure .ssh directory exists with correct permissions
mkdir -p /root/.ssh
chmod 700 /root/.ssh

if [ -f "$SSH_KEY" ]; then
    echo "[OK] SSH key exists at $SSH_KEY"
else
    echo "[INFO] Generating SSH key for container-to-host communication..."
    ssh-keygen -t rsa -b 4096 -f "$SSH_KEY" -N "" -q
    echo "[OK] SSH key generated"
fi

# Add key to authorized_keys if not already present
if [ -f "$SSH_KEY.pub" ]; then
    PUB_KEY=$(cat "$SSH_KEY.pub")
    if [ -f "$AUTHORIZED_KEYS" ] && grep -qF "$PUB_KEY" "$AUTHORIZED_KEYS" 2>/dev/null; then
        echo "[OK] SSH key already in authorized_keys"
    else
        echo "$PUB_KEY" >> "$AUTHORIZED_KEYS"
        chmod 600 "$AUTHORIZED_KEYS"
        echo "[OK] SSH key added to authorized_keys"
    fi
fi

# Test SSH connectivity to localhost
echo ""
echo "[INFO] Testing SSH connectivity to localhost..."
if ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=5 root@localhost "echo OK" 2>/dev/null; then
    echo "[OK] SSH to localhost working"
else
    echo "[WARN] SSH to localhost not working"
    echo "  Ensure sshd is running: systemctl start sshd"
    WARNINGS=$((WARNINGS + 1))
fi

# =============================================================================
# 5. Verify libvirt/kcli availability
# =============================================================================
echo ""
echo "[INFO] Checking virtualization prerequisites..."

# Check libvirtd
if systemctl is-active --quiet libvirtd 2>/dev/null; then
    echo "[OK] libvirtd is running"
else
    echo "[WARN] libvirtd is not running"
    echo "  Start with: systemctl start libvirtd"
    WARNINGS=$((WARNINGS + 1))
fi

# Check kcli
if command -v kcli &>/dev/null; then
    KCLI_VERSION=$(kcli version 2>/dev/null || echo "unknown")
    echo "[OK] kcli is installed (version: $KCLI_VERSION)"
else
    echo "[WARN] kcli is not installed"
    echo "  Install with: pip3 install kcli"
    WARNINGS=$((WARNINGS + 1))
fi

# =============================================================================
# Summary
# =============================================================================
echo ""
echo "========================================"
echo "Prerequisite Initialization Complete"
echo "========================================"
echo ""
echo "Results:"
echo "  - Errors: $ERRORS"
echo "  - Warnings: $WARNINGS"
echo ""

if [ $ERRORS -gt 0 ]; then
    echo "[ERROR] Some prerequisites could not be configured."
    echo "Please fix the errors above and re-run this script."
    exit 1
fi

if [ $WARNINGS -gt 0 ]; then
    echo "[WARN] Some optional prerequisites need attention."
    echo "The system may work but some features may be limited."
fi

echo ""
echo "Next steps:"
echo "  1. Review and update credentials in: $VAULT_FILE"
echo "  2. Start Airflow: cd $QUBINODE_DIR/airflow && podman-compose up -d"
echo "  3. Access Airflow UI: http://localhost:8888 (admin/admin)"
echo "  4. Trigger a DAG: freeipa_deployment, step_ca_deployment, etc."
echo ""
