---
- name: Setup KVM host
  hosts: control
  become: true
  tasks:
    - name: Ensure backup folder is created
      ansible.builtin.file:
        path: "{{ project_dir }}/backups"
        state: directory
        mode: '0755'

    - name: Checking to see if host_device is defined
      ansible.builtin.fail:
        msg: "Checking to see if host_device is defined."
      when: host_device is not defined

    - name: Checking to see if vg_name is defined
      ansible.builtin.fail:
        msg: "Checking to see if vg_name is defined."
      when: vg_name is not defined

    - name: Create libvirt logical volume
      ansible.builtin.include_role:
        name: tosin2013.qubinode_kvmhost_setup_collection.swygue_lvm
      when: create_lvm | bool

    - name: Running KVM host setup
      ansible.builtin.include_role:
        name: tosin2013.qubinode_kvmhost_setup_collection.kvmhost_setup

    - name: Validate KVM host setup
      ansible.builtin.include_role:
        name: tosin2013.qubinode_kvmhost_setup_collection.edge_hosts_validate
