---
# https://github.com/tosin2013/kcli-openshift4-baremetal/blob/master/paramfiles/lab.yml
# https://github.com/tosin2013/kcli-openshift4-baremetal/blob/master/plans/kcli_plan_default.yml
# Use n2.xlarge.x86 on Equinix
fake_network: true
pool: default
virtual_hub: true
version: stable
tag: "4.17"
dns: true
virtual_protocol: redfish
virtual_ctlplanes: true
launch_steps: true
deploy_openshift: true
installer_wait: true
cluster: lab
domain: example.com
baremetal_cidr: 192.168.130.0/24
baremetal_net: lab-baremetal
disk_size: 120
virtual_ctlplanes_memory: 16384
virtual_ctlplanes_numcpus: 8
virtual_workers: true
virtual_workers_memory: 48000
virtual_workers_number: 6
virtual_workers_numcpus: 12
virtual_workers_disksize: 120
extra_disks:
- size: 400
api_ip: 192.168.130.253
ingress_ip: 192.168.130.252
installer_ip: 192.168.130.20
baremetal_ips:
- 192.168.130.20
- 192.168.130.21
- 192.168.130.22
- 192.168.130.23
- 192.168.130.24
- 192.168.130.25
- 192.168.130.26
- 192.168.130.27
- 192.168.130.28
baremetal_macs:
- aa:aa:aa:aa:bb:01
- aa:aa:aa:aa:bb:02
- aa:aa:aa:aa:bb:03
- aa:aa:aa:aa:bb:04
- aa:aa:aa:aa:bb:05
- aa:aa:aa:aa:bb:06
- aa:aa:aa:aa:bb:07
- aa:aa:aa:aa:bb:08
- aa:aa:aa:aa:bb:09
notify: true
nfs: false
disconnected: false
