---
# Test Playbook for Qubinode Navigator Monitoring Callback Plugin
# This playbook demonstrates real-time monitoring capabilities

- name: "Qubinode Navigator Monitoring Test"
  hosts: localhost
  gather_facts: true
  vars:
    test_scenarios:
      - name: "System Information Gathering"
        duration: 2
      - name: "Service Status Check"
        duration: 3
      - name: "Resource Usage Monitoring"
        duration: 1

  tasks:
    - name: "Display deployment start message"
      debug:
        msg: "Starting Qubinode Navigator deployment with real-time monitoring"

    - name: "Gather system facts"
      setup:
      tags: [system_info]

    - name: "Test successful task execution"
      command: echo "Task completed successfully"
      register: success_result
      tags: [success_test]

    - name: "Test task with delay (performance monitoring)"
      pause:
        seconds: 5
      tags: [performance_test]

    - name: "Test conditional task execution"
      debug:
        msg: "This task runs conditionally"
      when: ansible_os_family == "RedHat"
      tags: [conditional_test]

    - name: "Simulate service check"
      service_facts:
      tags: [service_check]

    - name: "Test AI Assistant integration"
      uri:
        url: "http://localhost:8080/health"
        method: GET
        timeout: 10
      register: ai_health_check
      ignore_errors: true
      tags: [ai_integration]

    - name: "Display AI Assistant status"
      debug:
        msg: "AI Assistant Status: {{ 'Available' if ai_health_check.status == 200 else 'Unavailable' }}"
      when: ai_health_check is defined
      tags: [ai_integration]

    - name: "Test diagnostic tools integration"
      uri:
        url: "http://localhost:8080/diagnostics/tools"
        method: GET
        timeout: 10
      register: diagnostic_tools
      ignore_errors: true
      tags: [diagnostics_test]

    - name: "Display available diagnostic tools"
      debug:
        msg: "Available diagnostic tools: {{ diagnostic_tools.json.total_tools | default('N/A') }}"
      when: diagnostic_tools is defined and diagnostic_tools.status == 200
      tags: [diagnostics_test]

    - name: "Test intentional failure (for error handling)"
      command: /bin/false
      ignore_errors: true
      tags: [error_test]

    - name: "Display deployment completion message"
      debug:
        msg: "Qubinode Navigator deployment monitoring test completed"
