---
######################################
#         USER VARIABLES             #
# The are automatically updated or   #
# you can update them manually       #
######################################
# Config Directory
project_dir: /opt/qubinode-installer

# The name of the admin user for your system
admin_user: admin

# The domain name for your system
domain: "CHANGEME"

# RHEL Version
rhel_version: ""

#####
# RHPDS Settings
# Set run_on_rhpds to 'yes' to run your system on RHPDS.
# Set run_kni_lab_on_rhpds to 'yes' to run a KNI lab on RHPDS.
# Set one_redhat to 'yes' if you have a One Red Hat account.
#####
enable_cicd: 1
run_on_rhpds: false
run_kni_lab_on_rhpds: false
one_redhat: false


#####
# Application Dependencies
# Set ansible_automation_platform to 'true' to install the Ansible Automation Platform.
# Set enable_ceph_deployment to 'true' to enable Ceph deployment.
#####
ansible_automation_platform: false
enable_ceph_deployment: false

# PTR - The PTR record that should be used for your system
qubinode_ptr: changeme.in-addr.arpa

# Public DNS server
# The IP address of the DNS server that your system will use
dns_forwarder: "CHANGEME"

# swygue-redhat-subscription Role
# Set rhsm_reg_method to 'username_pass' to use a Red Hat account.
# Set rhsm_reg_method to 'rhsm' to use the Red Hat Subscription Manager.
rhsm_reg_method: ""

## When this var is set to true and the host gets it's ip address from
## dhcp. It was take that IP address and configure the host to use static
## ip address assignment. It's recommended that you create a DHCP reservation
## for this host to ensure the DHCP lease does not expire and get consume by
## another host on the network.
convert_dhcp_to_static: true

# ROLE: swygue-redhat-subscription
rhsm_org: "{{ rhsm_org }}"
rhsm_activationkey: "{{ rhsm_activationkey }}"
rhsm_org_id: "{{ rhsm_org }}"
rhsm_setup_insights_client: false
rhsm_user: "{{ rhsm_username }}"
rhsm_pass: "{{ rhsm_password }}"
org_id: "{{ rhsm_org }}"

# ROLE: swygue.edge_host_setup role
# the user that will admin the system
ssh_username: "{{ admin_user }}" # this var has been deprecated and should be removed

 # LVM
logical_volumes:
  - name: qubi_images
    size: "+100%FREE"
    mount_dir: "{{ kvm_host_libvirt_dir | default('/var/lib/libvirt/images') }}"
    fstype: xfs

# This is for KVM host initial setup of /etc/resolv.conf
required_rpm_packages:
  - virt-install
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - libguestfs-tools
  - libvirt-client
  - qemu-kvm
  - nfs-utils
  - libvirt-daemon
  - libvirt-client
  - virt-top
  - tuned
  - openssh-server
  - wget
  - git
  - net-tools
  - bind-utils
  - yum-utils
  - iptables-services
  - bash-completion
  - kexec-tools
  - sos
  - psacct
  - vim
  - device-mapper-event-libs
  - device-mapper-libs
  - httpd-tools
  - tmux
  - python3-dns
  - python3-lxml
  - cockpit-machines
  - bc
  - nmap
  - ncurses-devel
  - curl
