name: Configure RHEL 8 Equinix Server
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'hostname'
        required: true
        default: hostname
      target_server:
        description: 'target_server'
        required: true
        default: rhel8-equinix
env:
    TARGET_SERVER: ${{ inputs.target_server }}
    SSH_PASSWORD: ${{ inputs.ssh_password }}
   
jobs:
  configure-kcli-profiles:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Mask SSH_PASSWORD and then add to .env
      run: |
        echo "::add-mask::${{ env.SSH_PASSWORD }}"
    - name: Configure RHEL 8 Equinix Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.hostname }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          sudo yum install -y git
          if [ -d "/opt/quibinode_navigator" ]; then
            cd /opt/quibinode_navigator
            git config --global --add safe.directory /opt/quibinode_navigator
            git config pull.rebase false
            git pull
          else
            cd /opt/
            sudo usermod -aG users ${{ secrets.USERNAME }}
            sudo chown -R root:users /opt
            sudo chmod -R g+w /opt
            git clone https://github.com/tosin2013/quibinode_navigator.git
          fi
          echo "CICD_PIPELINE=true" > /opt/quibinode_navigator/.env
          echo "SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}" >> /opt/quibinode_navigator/.env
          echo "INVENTORY='${{ env.TARGET_SERVER }}'" >> /opt/quibinode_navigator/.env
          source /opt/quibinode_navigator/.env && sudo -E /opt/quibinode_navigator/rhel8-linux-hypervisor.sh || exit $?