name: Generate Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Document setup.sh
      id: action-genshdoc-setup
      uses: vargiuscuola/genshdoc@master
    - name: Github Action genshdoc
      id: action-genshdoc
      uses: vargiuscuola/genshdoc@master
      with:
        args: ./bash-aliases/
    - name: genshdoc result
      run: echo "The result of genshdoc Action was ${{ steps.action-genshdoc-setup.outputs.result }}"
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        ls -lath .
        cat REFERENCE.md
        echo "***************"
        cat REFERENCE-setup.md
        cat REFERENCE-setup-commands.md
        cat REFERENCE-configure-kcli.md
        cat REFERENCE-random-functions.md
        mkdir -p docs/REFERENCE
        mv REFERENCE* docs/REFERENCE/
        ls -lath docs/REFERENCE/