name: Generate Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Document setup.sh
      id: action-genshdoc-setup
      uses: vargiuscuola/genshdoc@master
    - name: Github Action genshdoc
      id: action-genshdoc
      uses: vargiuscuola/genshdoc@master
      with:
        args: ./bash-aliases/
    - name: genshdoc result
      run: echo "The result of genshdoc Action was ${{ steps.action-genshdoc-setup.outputs.result }}"
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        ls -lath .
        cat REFERENCE.md
        echo "***************"
        cat REFERENCE-setup.md
        cat REFERENCE-setup-commands.md
        cat REFERENCE-configure-kcli.md
        cat REFERENCE-random-functions.md
        mkdir -p docs/REFERENCE
        mv REFERENCE* docs/REFERENCE/
        ls -lath docs/REFERENCE/
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "CI: Automated build push" -a | exit 0
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        push-branch: main
        commit-message: 'Updating documentation'
        rebase: 'true' # pull and rebase before commit