# Clean, minimal Jekyll workflow that actually works
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install minimal build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ruby-full ruby-dev libgmp-dev libffi-dev
        
      - name: Setup Ruby and Bundler
        run: |
          echo "Ruby version: $(ruby --version)"
          gem install bundler
          echo "Bundler version: $(bundle --version)"
        
      - name: Install Jekyll dependencies
        working-directory: ./docs
        run: |
          # Configure bundler for native extensions
          bundle config set --local build.bigdecimal --with-gmp-dir=/usr
          bundle config set --local build.nokogiri --use-system-libraries
          bundle config set --local build.ffi --enable-system-libffi
          
          # Install gems
          bundle install --retry 3 --jobs 4
        
      - name: Build Jekyll site
        working-directory: ./docs
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
